Adds PartialEq trait implementation for IPLookupTable
bocharov/treebitmap pull request #2
Opened 2024-10-09 15:41 UTC by dipunj

2024-10-09 17:04 UTC, bocharov requested changes

2024-10-09 17:04 UTC, bocharov commented on src/lib.rs
> +    pub fn all(&self) -> Vec<(A, u32, &T)> {
I don't think we need new `all` method - any iterator can be collected into vector with `collect` right in equality method.

2024-10-09 17:04 UTC, bocharov commented on src/lib.rs
> +        let mut self_entries: Vec<(A, u32, &T)> = self.all();
Consider using iterators comparison: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.eq
Not sure, if we need to sort, the insertion order may matter in some cases.

2024-10-09 17:04 UTC, bocharov commented on src/lib.rs
> +        assert_ne!(tbl1, tbl5);
Add some IPv6 test cases and mix of IPv4 and IPv6.

2024-10-09 17:34 UTC, dipunj commented on src/lib.rs
> +        let mut self_entries: Vec<(A, u32, &T)> = self.all();
Regarding sorting, my initial implementation of equality focused on comparing the end nodes of two tables, which is sufficient for our specific use case since we only care about the end nodes.

However, after reviewing the rest of the code for the lookup table, I see it also supports partial matching. In this case, my notion of equality is insufficient because equality must account for the internal representation of the trie as well. 

Therefore, I propose removing the `PartialEq` trait and moving the end-node-based comparison to a dedicated method within the `IpLookupTable` implementation, as this better reflects its intended use.

@bocharov Thoughts?

2024-10-09 17:35 UTC, dipunj commented on src/lib.rs
> +    pub fn all(&self) -> Vec<(A, u32, &T)> {
fixed.

2024-10-09 17:36 UTC, dipunj commented on src/lib.rs
> +        assert_ne!(tbl1, tbl5);
Added some Ipv6 cases. I couldn't add a mix of IPv4 and IPv6 as their types would be different and the lookup table can either be ipv4 or ipv6 but not both at the same time.

2024-10-10 16:52 UTC, bocharov approved these changes

2024-10-10 16:53 UTC, merged